---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openwebui-secret-key
  namespace: ai-apps
spec:
  encryptedData:
    secret-key: AgC3loNvK1avPfoihbP8b7h+745Bxlc0vFW7j9doIyOVCnU/qXrlAybp1nyRJtpbrO21jWtsw6L4L7IvFSFJgXzmczTwQKlSuE1jvfVwIl69/TtDEcQiyaDyNe7dC3flFfD5wcUfpNy8/kb83FShiHlZu/IptyE+kKR/8vo5nb5/K/WCKWWrinuOmK53oslXsg5yuSyZgutNHmzAVugdk52Be02dkaA1YYVSTevy5JZHgrXPe2C0FWEOm3Z3ttvjqLT9BNQa6TYbpX6Q9aoZDFQpKy1iM4CJUkGfb8DT0ZWriOYF263JIskWTpCm1BmS+fuEvQ5veYIU3C86gT6JdJYzbNImqvnb+APVdKvpoZuv8wWq5a62F9btzidydgQa8ecWmM0BwUdEP8toCcFI4b8G+Ad4R/eO3CR/2KFobfh21/d+fnNp3MIDrVK/1q/Q4Wf/p/pvlOj+yLmxWI/uSiotftUCaW/LsOS0gT+K+53txi6We8aQonP5paX3kUY7Xp+DKy1ZpUkieiTWmONKM0I6YETJFrNfagdZ2w6xAPCT1CTbkdwiTSC+NNXcLZnY7ho//LkXii2NH+Vq0dX/6htW8ltUJS6T1nyI6r0btImxFRzOwGW184iku81c+xVE6ubQ3UyCIiV5Fn9suZakyhka/eNIQTfv4/rEiI9/9bFwiLmcxXkbwLGWnSxQ3fOSQ9Y2nKD2Dr5aZNZv7MM1otstcoVxyu6SG/w9yIj6bzQkkQHInqt024X0wTA4bnVZXB7KO864mlRYn45BfMpTwwMe
  template:
    metadata:
      creationTimestamp: null
      name: openwebui-secret-key
      namespace: ai-apps
    type: Opaque
