---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openwebui-oidc-secret
  namespace: ai-apps
spec:
  encryptedData:
    client-secret: AgCf19b4qrUobCvpP/WtTN83Ki3zK4XX7OEGJUlNAomW7k0r5mM1wSXRIMfVc6tjmFe1/ypBmzEmuJyv6KOFaz75GqZotm1pynvM4UKmhVZYGssHyM49aY/fG1Nh3wPVcOJpJScP4BqVgb1gF3LktsCVDoTnI0ISjFrBHX7Rmxga1RlxDjNoHMbZZcFnOT32sxtDpj9pyIPsry8Di+vC5lmfR/KcSKzeR0RY2hfSUOkzBEpMyEutm2NHlDp66G0ddXVm1mP1Fvzr2ZWe41200ipQQ0htehtLmUw1plSS9KuAnrazpGWU1iGU4BifZVSytoO7IUlKmL9hrfWjSGEtVMDUk1vU2ksxL8/vBXSAW9uvWo5WyBASJGhprlsoBveIAgnztWz0mZEOBCqAtefjVxjfDojd89pB4QDzz80MvVinjWVGn5eZFK1D9s2fBs5Z0Ko3cLYIo7eyXLiGqJfrpuCHgKMzH/DId/NcLxGAW8kh6jCgJLm76qSJxOHGP554LpqIWynhF66PRB5SSQyyC86+glD97C65bGnGMDheAMSAsI4hGrWQ0X0TlT6WDiM19ZVzB7vBn6gTGDClUjX+wSQ+j/xaBnaViaTAxbLh/FSufdeU8/1FNZ4s5uBoF387vPEvVr/u3pExSX5hJpRJ8PbL3BewDyMkDtv/Z6XMQKXcSXgSNdG0Q2nk4vi/vN7Yo2h6MDS3mwLxdrvCbmkl+dfIYl4YsYeCYZTApjf727OY3Q==
  template:
    metadata:
      creationTimestamp: null
      name: openwebui-oidc-secret
      namespace: ai-apps
