apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: keycloak-rbac
  labels:
    app.kubernetes.io/part-of: ai-security-platform

resources:
  - clusterroles.yaml
  - clusterrolebindings.yaml
  - rolebindings.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: ai-security-platform
